p = patch([ixb, Nx, Nx, ixb],[ylims(1), ylims(1), ylims(2), ylims(2)],'k');
set(p,'FaceAlpha',0.1,'EdgeColor','none');
set(gca,'YLim',ylims)
if 0
    text(1,ylims(1),'$Z_1 = \sqrt{\mu_o/\epsilon_o}$',...
        'VerticalAlign','Bottom',...
        'Interpreter','LaTeX');
    text(Nx,ylims(1),'$Z_2 = Z_1/3$',...
        'VerticalAlign','Bottom','HorizontalAlign','Right',...
        'Interpreter','LaTeX');
end